
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/

    instance:
      localhost

  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
